
on:
  # Only run on Push commits to the Main branch
  push:
    branches:
      - main

name: 'Version'
jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      # Checkout main branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      # Version control
      - name: Bump Version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'main'
          minor-wording: 'MINOR,minor'
          major-wording: 'MAJOR,major'
          patch-wording: 'PATCH,patch'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

      # Publish to packagist
      - name: curl
        uses: wei/curl@v1
        with:
          args: -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=dmccleery&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/daltonmccleery/laravel-quick-start"}}'